### ISSUE TITLE
ngc: Error: Unexpected value 'DynamicComponentModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by scottopolis** [apoterenko/angular2-dynamic-component#10]
Hopefully my last issue ;)

I'm using rollup.js as my compiler (with Ionic 2), which uses AoT compiling. I'm getting this error:

`ngc: Error: Unexpected value 'DynamicComponentModule' imported by the module 'AppModule'`

I'm using the standard import from your docs in my module:

`import {DynamicComponentModule} from 'angular2-dynamic-component/index';`

Any idea how to fix?

Thanks!

**Comment by apoterenko** [comment]
Wow.

Maybe try it using require(..)?

**Comment by scottopolis** [comment]
Using require gives me this error:

```
ngc: Error: Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule
```

It might be this issue: https://github.com/rollup/rollup/issues/447

Or it might be because DynamicComponentModule doesn't support AoT compiling.  Not quite sure how to fix.

**Comment by apoterenko** [comment]
I am not sure, but Try to use this plugin

https://github.com/rollup/rollup-plugin-commonjs

**Comment by scottopolis** [comment]
That didn't work for me, I think this is an issue with [ngc](https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli), not rollup.  You aren't seeing this error using ngc?

**Comment by apoterenko** [comment]
I didn't see this issue never before

**Comment by apoterenko** [comment]
I've built the package using ngc (0.1.1).
Please, let me know if you have some other troubles, thanks

**Comment by scottopolis** [comment]
Thanks for the update, I'm not getting that other error anymore, but I am seeing this:

```
[08:29:38]  Error: Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:24:25
[08:29:38]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[08:29:38]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:47:66
[08:29:38]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[08:29:38]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:47:124
[08:29:38]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[08:29:38]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:50:55
[08:29:38]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[08:29:38]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:60:157
[08:29:38]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[08:29:38]  Error at /.tmp/pages/custom-pages/custom-page.ngfactory.ts:106:26
[08:29:38]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[08:29:38]  Error at /.tmp/pages/custom-pages/custom-page.ngfactory.ts:279:41
[08:29:38]  Property 'extraModules' is private and only accessible within class 'CustomPage'.
[08:29:38]  ngc failed
[08:29:38]  ionic-app-script task: "build"
[08:29:38]  Error: Error
```

**Comment by apoterenko** [comment]
<Property 'extraModules' is private and only accessible within class 'CustomPage'.>

It looks like your project compilation error.

And DynamicComponent.ngfactory.ts - is a part of src directory. Imho, you should not compile *.ts within submodules

**Comment by scottopolis** [comment]
I don't really know what this means: Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s)

Am I missing an input argument in my code?  I'm using it similar to your examples:

```
@Component({
  template: '<DynamicComponent [componentTemplateUrl]="templateUrl"></DynamicComponent>'
})
export class CustomPage {

	templateUrl: string = 'mypage.html';

}
```

Any idea how to fix?

**Comment by apoterenko** [comment]
Please check 0.1.2 (Generic type 'DynamicComponent' the error must disappear)

PS
Apparently, ngc have compiled sources with error

"new import 12.ComponentFactory <import3.DynamicComponent <IS_ABSENT_BUT_SHOULD_BE_FILLED >>"

**Comment by scottopolis** [comment]
Updated to 0.1.2, same errors.

**Comment by apoterenko** [comment]
Please provide again full error log here

**Comment by scottopolis** [comment]
[12:19:57]  Error: Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:24:25
[12:19:57]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[12:19:57]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:47:66
[12:19:57]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[12:19:57]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:47:124
[12:19:57]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[12:19:57]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:50:55
[12:19:57]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[12:19:57]  Error at /.tmp/node_modules/angular2-dynamic-component/DynamicComponent.ngfactory.ts:60:157
[12:19:57]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[12:19:57]  Error at /.tmp/pages/custom-pages/custom-page.ngfactory.ts:106:26
[12:19:57]  Generic type 'DynamicComponent<TDynamicComponentType>' requires 1 type argument(s).
[12:19:57]  ngc failed
[12:19:57]  ionic-app-script task: "build"
[12:19:57]  Error: Error

**Comment by apoterenko** [comment]
It's strange, but the errors ts:24:25 + ts:47:66 + .ts:47:124 + .ts:50:55 + .ts:60:157 should disappear at 0.1.2 because I have uploaded the modified files (at 0.1.2). It looks like (https://github.com/apoterenko/angular2-dynamic-component/commit/6782cf8fbf4f9a63dc61a2f67da779169e85a0b4)

**Another**** thing - :106:26 error** => I have deleted entirely Generic from DynamicComponent declaration at 0.1.3

**Comment by apoterenko** [comment]
See https://github.com/apoterenko/angular2-dynamic-component/commit/747c1a02af9f58666c90e0601f6a3c2c4e34748f

**Comment by scottopolis** [comment]
All fixed now, thanks so much for your help!

FYI: v 0.1.3 installs but says 'invalid'

Also I can't use a constructor in my class or it says "signature does not match call target."  Is that fixable?

Anyways it builds with Ionic/ngc now, so thanks!

**Comment by apoterenko** [comment]
"Also I can't use a constructor in my class or it says "signature does not match call target." Is that fixable?"

can you provide the code?

**Comment by apoterenko** [comment]
"FYI: v 0.1.3 installs but says 'invalid'"

can you provide the error message??
